### ISSUE TITLE
An error occured. You can get details from programm log file.

### ISSUE THREAD

**Issue by TKFRvisionOfficial** [sovworks/edslite#17]
Where is that file? And what does the error mean?
Trying to open veracrypt container!!!

**Comment by beroal** [comment]
I have the same issue. I am trying to open LUKS 1 created on ArchLinux.

**Comment by beroal** [comment]
Okay, here the “program log file” means the system log that can be viewed with Logcat. In order to see the message, you need to install any Logcat viewer like “Logcat Reader”, give it the right to read logs, restart Android, add a filter with “Tag” equal to “EDS” and the “Warning” checkmark. Then you will see something like
```
com.sovworks.eds.exceptions.UnsupportedContainerTypeException: Unsupported container format version 2
	at com.sovworks.eds.luks.VolumeLayout.deserializeHeaderData(VolumeLayout.java:466)
	at com.sovworks.eds.luks.VolumeLayout.readHeader(VolumeLayout.java:85)
[skipped]
```
in the log.
